package bazaKontrola;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
//import java.sql.Statement;


public class BazaKontrolaPolaczenie {
	public static Connection pol = null;
    private static String user = "root";
    private static String password = "";
 //   private static Statement stmt;
    public static Connection getPol() throws Throwable {
        if (pol == null) {
            try {
                String driver = "com.mysql.jdbc.Driver";
                Class.forName(driver).newInstance();
                pol = DriverManager.getConnection("jdbc:mysql://localhost:3306/sklep?characterEncoding=UTF-8", user, password);
            } catch (SQLException ex) {
              
            } catch (InstantiationException ex) {
               
            } catch (IllegalAccessException ex) {
             
            } catch (ClassNotFoundException ex) {
             
            }
        }
        
       /* boolean exists = false;
        if(!exists)
		{
			stmt.executeUpdate(""
					+ "CREATE TABLE product("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
					+ "name varchar(50),"
					+ "description varchar(500),"
					+ "prize double,"
					+ ")");
			
		}*/
        return pol;
    }

    public static void killConnection() {
        if (pol != null) {
            try {
                pol.close();
            } catch (SQLException ex) {
              
            }
        }
    }


}